# Generated by Django 4.1.7 on 2023-03-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Csv_Task_1', '0002_alter_address_pin_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='last_date',
            new_name='last_update',
        ),
    ]
